/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.LocalDate;

import com.weatherapi.api.*;
import com.weatherapi.api.models.*;
import com.weatherapi.api.exceptions.*;
import com.weatherapi.api.http.client.HttpClient;
import com.weatherapi.api.http.client.HttpContext;
import com.weatherapi.api.http.request.HttpRequest;
import com.weatherapi.api.http.response.HttpResponse;
import com.weatherapi.api.http.response.HttpStringResponse;
import com.weatherapi.api.http.client.APICallBack;
import com.weatherapi.api.controllers.syncwrapper.APICallBackCatcher;

public class APIsController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static APIsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the APIsController class 
     */
    public static APIsController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new APIsController();
                }
            }
        }
        return instance;
    }

    /**
     * Current weather or realtime weather API method allows a user to get up to date current weather information in json and xml. The data is returned as a Current Object.Current object contains current or realtime weather information for a given city.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     * @return    Returns the CurrentJsonResponse response from the API call 
     */
    public CurrentJsonResponse getRealtimeWeather(
                final String q,
                final String lang
    ) throws Throwable {

        HttpRequest _request = _buildGetRealtimeWeatherRequest(q, lang);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetRealtimeWeatherResponse(_context);
    }

    /**
     * Current weather or realtime weather API method allows a user to get up to date current weather information in json and xml. The data is returned as a Current Object.Current object contains current or realtime weather information for a given city.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     */
    public void getRealtimeWeatherAsync(
                final String q,
                final String lang,
                final APICallBack<CurrentJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetRealtimeWeatherRequest(q, lang);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            CurrentJsonResponse returnValue = _handleGetRealtimeWeatherResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getRealtimeWeather
     */
    private HttpRequest _buildGetRealtimeWeatherRequest(
                final String q,
                final String lang) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/current.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        if (lang != null) {
            _queryParameters.put("lang", lang);
        }
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getRealtimeWeather
     * @return An object of type CurrentJsonResponse
     */
    private CurrentJsonResponse _handleGetRealtimeWeatherResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        CurrentJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<CurrentJsonResponse>(){});

        return _result;
    }

    /**
     * Forecast weather API method returns upto next 10 day weather forecast and weather alert as json. The data is returned as a Forecast Object.<br />Forecast object contains astronomy data, day weather forecast and hourly interval weather information for a given city.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    days    Required parameter: Number of days of weather forecast. Value ranges from 1 to 10
     * @param    dt    Optional parameter: Date should be between today and next 10 day in yyyy-MM-dd format
     * @param    unixdt    Optional parameter: Please either pass 'dt' or 'unixdt' and not both in same request.<br />unixdt should be between today and next 10 day in Unix format
     * @param    hour    Optional parameter: Must be in 24 hour. For example 5 pm should be hour=17, 6 am as hour=6
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     * @return    Returns the ForecastJsonResponse response from the API call 
     */
    public ForecastJsonResponse getForecastWeather(
                final String q,
                final int days,
                final LocalDate dt,
                final Integer unixdt,
                final Integer hour,
                final String lang
    ) throws Throwable {

        HttpRequest _request = _buildGetForecastWeatherRequest(q, days, dt, unixdt, hour, lang);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetForecastWeatherResponse(_context);
    }

    /**
     * Forecast weather API method returns upto next 10 day weather forecast and weather alert as json. The data is returned as a Forecast Object.<br />Forecast object contains astronomy data, day weather forecast and hourly interval weather information for a given city.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    days    Required parameter: Number of days of weather forecast. Value ranges from 1 to 10
     * @param    dt    Optional parameter: Date should be between today and next 10 day in yyyy-MM-dd format
     * @param    unixdt    Optional parameter: Please either pass 'dt' or 'unixdt' and not both in same request.<br />unixdt should be between today and next 10 day in Unix format
     * @param    hour    Optional parameter: Must be in 24 hour. For example 5 pm should be hour=17, 6 am as hour=6
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     */
    public void getForecastWeatherAsync(
                final String q,
                final int days,
                final LocalDate dt,
                final Integer unixdt,
                final Integer hour,
                final String lang,
                final APICallBack<ForecastJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetForecastWeatherRequest(q, days, dt, unixdt, hour, lang);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            ForecastJsonResponse returnValue = _handleGetForecastWeatherResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getForecastWeather
     */
    private HttpRequest _buildGetForecastWeatherRequest(
                final String q,
                final int days,
                final LocalDate dt,
                final Integer unixdt,
                final Integer hour,
                final String lang) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/forecast.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("days", days);
        if (dt != null) {
            _queryParameters.put("dt", DateTimeHelper.toSimpleDate(dt));
        }
        if (unixdt != null) {
            _queryParameters.put("unixdt", unixdt);
        }
        if (hour != null) {
            _queryParameters.put("hour", hour);
        }
        if (lang != null) {
            _queryParameters.put("lang", lang);
        }
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getForecastWeather
     * @return An object of type ForecastJsonResponse
     */
    private ForecastJsonResponse _handleGetForecastWeatherResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        ForecastJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<ForecastJsonResponse>(){});

        return _result;
    }

    /**
     * History weather API method returns historical weather for a date on or after 1st Jan, 2015 as json. The data is returned as a Forecast Object.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    dt    Required parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format
     * @param    unixdt    Optional parameter: Please either pass 'dt' or 'unixdt' and not both in same request.<br />unixdt should be on or after 1st Jan, 2015 in Unix format
     * @param    endDt    Optional parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format'end_dt' should be greater than 'dt' parameter and difference should not be more than 30 days between the two dates.
     * @param    unixendDt    Optional parameter: Date on or after 1st Jan, 2015 in Unix Timestamp format<br />unixend_dt has same restriction as 'end_dt' parameter. Please either pass 'end_dt' or 'unixend_dt' and not both in same request. e.g.: unixend_dt=1490227200
     * @param    hour    Optional parameter: Must be in 24 hour. For example 5 pm should be hour=17, 6 am as hour=6
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     * @return    Returns the HistoryJsonResponse response from the API call 
     */
    public HistoryJsonResponse getHistoryWeather(
                final String q,
                final LocalDate dt,
                final Integer unixdt,
                final LocalDate endDt,
                final Integer unixendDt,
                final Integer hour,
                final String lang
    ) throws Throwable {

        HttpRequest _request = _buildGetHistoryWeatherRequest(q, dt, unixdt, endDt, unixendDt, hour, lang);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetHistoryWeatherResponse(_context);
    }

    /**
     * History weather API method returns historical weather for a date on or after 1st Jan, 2015 as json. The data is returned as a Forecast Object.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    dt    Required parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format
     * @param    unixdt    Optional parameter: Please either pass 'dt' or 'unixdt' and not both in same request.<br />unixdt should be on or after 1st Jan, 2015 in Unix format
     * @param    endDt    Optional parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format'end_dt' should be greater than 'dt' parameter and difference should not be more than 30 days between the two dates.
     * @param    unixendDt    Optional parameter: Date on or after 1st Jan, 2015 in Unix Timestamp format<br />unixend_dt has same restriction as 'end_dt' parameter. Please either pass 'end_dt' or 'unixend_dt' and not both in same request. e.g.: unixend_dt=1490227200
     * @param    hour    Optional parameter: Must be in 24 hour. For example 5 pm should be hour=17, 6 am as hour=6
     * @param    lang    Optional parameter: Returns 'condition:text' field in API in the desired language. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to check 'lang-code'.
     */
    public void getHistoryWeatherAsync(
                final String q,
                final LocalDate dt,
                final Integer unixdt,
                final LocalDate endDt,
                final Integer unixendDt,
                final Integer hour,
                final String lang,
                final APICallBack<HistoryJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetHistoryWeatherRequest(q, dt, unixdt, endDt, unixendDt, hour, lang);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            HistoryJsonResponse returnValue = _handleGetHistoryWeatherResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getHistoryWeather
     */
    private HttpRequest _buildGetHistoryWeatherRequest(
                final String q,
                final LocalDate dt,
                final Integer unixdt,
                final LocalDate endDt,
                final Integer unixendDt,
                final Integer hour,
                final String lang) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/history.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("dt", DateTimeHelper.toSimpleDate(dt));
        if (unixdt != null) {
            _queryParameters.put("unixdt", unixdt);
        }
        if (endDt != null) {
            _queryParameters.put("end_dt", DateTimeHelper.toSimpleDate(endDt));
        }
        if (unixendDt != null) {
            _queryParameters.put("unixend_dt", unixendDt);
        }
        if (hour != null) {
            _queryParameters.put("hour", hour);
        }
        if (lang != null) {
            _queryParameters.put("lang", lang);
        }
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getHistoryWeather
     * @return An object of type HistoryJsonResponse
     */
    private HistoryJsonResponse _handleGetHistoryWeatherResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        HistoryJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<HistoryJsonResponse>(){});

        return _result;
    }

    /**
     * WeatherAPI.com Search or Autocomplete API returns matching cities and towns as an array of Location object.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @return    Returns the List<SearchJsonResponse> response from the API call 
     */
    public List<SearchJsonResponse> searchAutocompleteWeather(
                final String q
    ) throws Throwable {

        HttpRequest _request = _buildSearchAutocompleteWeatherRequest(q);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleSearchAutocompleteWeatherResponse(_context);
    }

    /**
     * WeatherAPI.com Search or Autocomplete API returns matching cities and towns as an array of Location object.
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     */
    public void searchAutocompleteWeatherAsync(
                final String q,
                final APICallBack<List<SearchJsonResponse>> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildSearchAutocompleteWeatherRequest(q);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            List<SearchJsonResponse> returnValue = _handleSearchAutocompleteWeatherResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for searchAutocompleteWeather
     */
    private HttpRequest _buildSearchAutocompleteWeatherRequest(
                final String q) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/search.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for searchAutocompleteWeather
     * @return An object of type List<SearchJsonResponse>
     */
    private List<SearchJsonResponse> _handleSearchAutocompleteWeatherResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        List<SearchJsonResponse> _result = APIHelper.deserialize(_responseBody,
									new TypeReference<List<SearchJsonResponse>>(){});

        return _result;
    }

    /**
     * IP Lookup API method allows a user to get up to date information for an IP address.
     * @param    q    Required parameter: Pass IP address.
     * @return    Returns the IpJsonResponse response from the API call 
     */
    public IpJsonResponse getIpLookup(
                final String q
    ) throws Throwable {

        HttpRequest _request = _buildGetIpLookupRequest(q);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetIpLookupResponse(_context);
    }

    /**
     * IP Lookup API method allows a user to get up to date information for an IP address.
     * @param    q    Required parameter: Pass IP address.
     */
    public void getIpLookupAsync(
                final String q,
                final APICallBack<IpJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetIpLookupRequest(q);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            IpJsonResponse returnValue = _handleGetIpLookupResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getIpLookup
     */
    private HttpRequest _buildGetIpLookupRequest(
                final String q) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/ip.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getIpLookup
     * @return An object of type IpJsonResponse
     */
    private IpJsonResponse _handleGetIpLookupResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        IpJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<IpJsonResponse>(){});

        return _result;
    }

    /**
     * Return Location Object
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @return    Returns the TimezoneJsonResponse response from the API call 
     */
    public TimezoneJsonResponse getTimeZone(
                final String q
    ) throws Throwable {

        HttpRequest _request = _buildGetTimeZoneRequest(q);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetTimeZoneResponse(_context);
    }

    /**
     * Return Location Object
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     */
    public void getTimeZoneAsync(
                final String q,
                final APICallBack<TimezoneJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetTimeZoneRequest(q);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            TimezoneJsonResponse returnValue = _handleGetTimeZoneResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getTimeZone
     */
    private HttpRequest _buildGetTimeZoneRequest(
                final String q) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/timezone.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getTimeZone
     * @return An object of type TimezoneJsonResponse
     */
    private TimezoneJsonResponse _handleGetTimeZoneResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        TimezoneJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<TimezoneJsonResponse>(){});

        return _result;
    }

    /**
     * Return Location and Astronomy Object
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    dt    Required parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format
     * @return    Returns the AstronomyJsonResponse response from the API call 
     */
    public AstronomyJsonResponse getAstronomy(
                final String q,
                final LocalDate dt
    ) throws Throwable {

        HttpRequest _request = _buildGetAstronomyRequest(q, dt);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetAstronomyResponse(_context);
    }

    /**
     * Return Location and Astronomy Object
     * @param    q    Required parameter: Pass US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name. Visit [request parameter section](https://www.weatherapi.com/docs/#intro-request) to learn more.
     * @param    dt    Required parameter: Date on or after 1st Jan, 2015 in yyyy-MM-dd format
     */
    public void getAstronomyAsync(
                final String q,
                final LocalDate dt,
                final APICallBack<AstronomyJsonResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetAstronomyRequest(q, dt);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            AstronomyJsonResponse returnValue = _handleGetAstronomyResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getAstronomy
     */
    private HttpRequest _buildGetAstronomyRequest(
                final String q,
                final LocalDate dt) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/astronomy.json");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("q", q);
        _queryParameters.put("dt", DateTimeHelper.toSimpleDate(dt));
        _queryParameters.put("key", Configuration.key);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getAstronomy
     * @return An object of type AstronomyJsonResponse
     */
    private AstronomyJsonResponse _handleGetAstronomyResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new APIException("Error code 1003: Parameter 'q' not provided.Error code 1005: API request url is invalid.Error code 1006: No location found matching parameter 'q'Error code 9999: Internal application error.", _context);
        }
        if (_responseCode == 401) {
            throw new APIException("Error code 1002: API key not provided.Error code 2006: API key provided is invalid", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Error code 2007: API key has exceeded calls per month quota.<br />Error code 2008: API key has been disabled.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        AstronomyJsonResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<AstronomyJsonResponse>(){});

        return _result;
    }

}
