/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class AstroBuilder {
    //the instance to build
    private Astro astro;

    /**
     * Default constructor to initialize the instance
     */
    public AstroBuilder() {
        astro = new Astro();
    }

    /**
     * Sunrise time
     */
    public AstroBuilder sunrise(String sunrise) {
        astro.setSunrise(sunrise);
        return this;
    }

    /**
     * Sunset time
     */
    public AstroBuilder sunset(String sunset) {
        astro.setSunset(sunset);
        return this;
    }

    /**
     * Moonrise time
     */
    public AstroBuilder moonrise(String moonrise) {
        astro.setMoonrise(moonrise);
        return this;
    }

    /**
     * Moonset time
     */
    public AstroBuilder moonset(String moonset) {
        astro.setMoonset(moonset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Astro build() {
        return astro;
    }
}