/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class AstronomyJsonResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2218542006649064106L;
    private Location location;
    private Astronomy astronomy;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("location")
    public Location getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("location")
    public void setLocation (Location value) { 
        this.location = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("astronomy")
    public Astronomy getAstronomy ( ) { 
        return this.astronomy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("astronomy")
    public void setAstronomy (Astronomy value) { 
        this.astronomy = value;
    }
 
}
