/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class ConditionBuilder {
    //the instance to build
    private Condition condition;

    /**
     * Default constructor to initialize the instance
     */
    public ConditionBuilder() {
        condition = new Condition();
    }

    /**
     * Weather condition text
     */
    public ConditionBuilder text(String text) {
        condition.setText(text);
        return this;
    }

    /**
     * Weather icon url
     */
    public ConditionBuilder icon(String icon) {
        condition.setIcon(icon);
        return this;
    }

    /**
     * Weather condition unique code.
     */
    public ConditionBuilder code(Integer code) {
        condition.setCode(code);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Condition build() {
        return condition;
    }
}