/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class CurrentJsonResponseBuilder {
    //the instance to build
    private CurrentJsonResponse currentJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CurrentJsonResponseBuilder() {
        currentJsonResponse = new CurrentJsonResponse();
    }

    public CurrentJsonResponseBuilder location(Location location) {
        currentJsonResponse.setLocation(location);
        return this;
    }

    public CurrentJsonResponseBuilder current(Current current) {
        currentJsonResponse.setCurrent(current);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CurrentJsonResponse build() {
        return currentJsonResponse;
    }
}