/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class ForecastBuilder {
    //the instance to build
    private Forecast forecast;

    /**
     * Default constructor to initialize the instance
     */
    public ForecastBuilder() {
        forecast = new Forecast();
    }

    public ForecastBuilder forecastday(List<Forecastday> forecastday) {
        forecast.setForecastday(forecastday);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Forecast build() {
        return forecast;
    }
}