/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class Forecastday1Builder {
    //the instance to build
    private Forecastday1 forecastday1;

    /**
     * Default constructor to initialize the instance
     */
    public Forecastday1Builder() {
        forecastday1 = new Forecastday1();
    }

    /**
     * Forecast date
     */
    public Forecastday1Builder date(String date) {
        forecastday1.setDate(date);
        return this;
    }

    /**
     * Forecast date as unix time.
     */
    public Forecastday1Builder dateEpoch(Integer dateEpoch) {
        forecastday1.setDateEpoch(dateEpoch);
        return this;
    }

    /**
     * See day element
     */
    public Forecastday1Builder day(Day day) {
        forecastday1.setDay(day);
        return this;
    }

    public Forecastday1Builder astro(Astro astro) {
        forecastday1.setAstro(astro);
        return this;
    }

    public Forecastday1Builder hour(List<Hour> hour) {
        forecastday1.setHour(hour);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Forecastday1 build() {
        return forecastday1;
    }
}