/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class HistoryJsonResponseBuilder {
    //the instance to build
    private HistoryJsonResponse historyJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public HistoryJsonResponseBuilder() {
        historyJsonResponse = new HistoryJsonResponse();
    }

    public HistoryJsonResponseBuilder location(Location location) {
        historyJsonResponse.setLocation(location);
        return this;
    }

    public HistoryJsonResponseBuilder current(Current current) {
        historyJsonResponse.setCurrent(current);
        return this;
    }

    public HistoryJsonResponseBuilder forecast(Forecast1 forecast) {
        historyJsonResponse.setForecast(forecast);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public HistoryJsonResponse build() {
        return historyJsonResponse;
    }
}