/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class IpJsonResponseBuilder {
    //the instance to build
    private IpJsonResponse ipJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public IpJsonResponseBuilder() {
        ipJsonResponse = new IpJsonResponse();
    }

    /**
     * IP address
     */
    public IpJsonResponseBuilder ip(String ip) {
        ipJsonResponse.setIp(ip);
        return this;
    }

    /**
     * ipv4 or ipv6
     */
    public IpJsonResponseBuilder type(String type) {
        ipJsonResponse.setType(type);
        return this;
    }

    /**
     * Continent code
     */
    public IpJsonResponseBuilder continentCode(String continentCode) {
        ipJsonResponse.setContinentCode(continentCode);
        return this;
    }

    /**
     * Continent name
     */
    public IpJsonResponseBuilder continentName(String continentName) {
        ipJsonResponse.setContinentName(continentName);
        return this;
    }

    /**
     * Country code
     */
    public IpJsonResponseBuilder countryCode(String countryCode) {
        ipJsonResponse.setCountryCode(countryCode);
        return this;
    }

    /**
     * Name of country
     */
    public IpJsonResponseBuilder countryName(String countryName) {
        ipJsonResponse.setCountryName(countryName);
        return this;
    }

    /**
     * true or false
     */
    public IpJsonResponseBuilder isEu(Boolean isEu) {
        ipJsonResponse.setIsEu(isEu);
        return this;
    }

    /**
     * Geoname ID
     */
    public IpJsonResponseBuilder geonameId(Integer geonameId) {
        ipJsonResponse.setGeonameId(geonameId);
        return this;
    }

    /**
     * City name
     */
    public IpJsonResponseBuilder city(String city) {
        ipJsonResponse.setCity(city);
        return this;
    }

    /**
     * Region name
     */
    public IpJsonResponseBuilder region(String region) {
        ipJsonResponse.setRegion(region);
        return this;
    }

    /**
     * Latitude in decimal degree
     */
    public IpJsonResponseBuilder lat(Double lat) {
        ipJsonResponse.setLat(lat);
        return this;
    }

    /**
     * Longitude in decimal degree
     */
    public IpJsonResponseBuilder lon(Double lon) {
        ipJsonResponse.setLon(lon);
        return this;
    }

    /**
     * Time zone
     */
    public IpJsonResponseBuilder tzId(String tzId) {
        ipJsonResponse.setTzId(tzId);
        return this;
    }

    /**
     * Local time as epoch
     */
    public IpJsonResponseBuilder localtimeEpoch(Integer localtimeEpoch) {
        ipJsonResponse.setLocaltimeEpoch(localtimeEpoch);
        return this;
    }

    /**
     * Date and time
     */
    public IpJsonResponseBuilder localtime(String localtime) {
        ipJsonResponse.setLocaltime(localtime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public IpJsonResponse build() {
        return ipJsonResponse;
    }
}