/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class SearchJsonResponseBuilder {
    //the instance to build
    private SearchJsonResponse searchJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchJsonResponseBuilder() {
        searchJsonResponse = new SearchJsonResponse();
    }

    public SearchJsonResponseBuilder id(Integer id) {
        searchJsonResponse.setId(id);
        return this;
    }

    /**
     * Local area name.
     */
    public SearchJsonResponseBuilder name(String name) {
        searchJsonResponse.setName(name);
        return this;
    }

    /**
     * Local area region.
     */
    public SearchJsonResponseBuilder region(String region) {
        searchJsonResponse.setRegion(region);
        return this;
    }

    /**
     * Country
     */
    public SearchJsonResponseBuilder country(String country) {
        searchJsonResponse.setCountry(country);
        return this;
    }

    /**
     * Area latitude
     */
    public SearchJsonResponseBuilder lat(Double lat) {
        searchJsonResponse.setLat(lat);
        return this;
    }

    /**
     * Area longitude
     */
    public SearchJsonResponseBuilder lon(Double lon) {
        searchJsonResponse.setLon(lon);
        return this;
    }

    public SearchJsonResponseBuilder url(String url) {
        searchJsonResponse.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchJsonResponse build() {
        return searchJsonResponse;
    }
}