/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

import java.util.*;

public class TimezoneJsonResponseBuilder {
    //the instance to build
    private TimezoneJsonResponse timezoneJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TimezoneJsonResponseBuilder() {
        timezoneJsonResponse = new TimezoneJsonResponse();
    }

    /**
     * Local area name.
     */
    public TimezoneJsonResponseBuilder name(String name) {
        timezoneJsonResponse.setName(name);
        return this;
    }

    /**
     * Local area region.
     */
    public TimezoneJsonResponseBuilder region(String region) {
        timezoneJsonResponse.setRegion(region);
        return this;
    }

    /**
     * Country
     */
    public TimezoneJsonResponseBuilder country(String country) {
        timezoneJsonResponse.setCountry(country);
        return this;
    }

    /**
     * Area latitude
     */
    public TimezoneJsonResponseBuilder lat(Double lat) {
        timezoneJsonResponse.setLat(lat);
        return this;
    }

    /**
     * Area longitude
     */
    public TimezoneJsonResponseBuilder lon(Double lon) {
        timezoneJsonResponse.setLon(lon);
        return this;
    }

    /**
     * Time zone
     */
    public TimezoneJsonResponseBuilder tzId(String tzId) {
        timezoneJsonResponse.setTzId(tzId);
        return this;
    }

    /**
     * Local date and time in unix time
     */
    public TimezoneJsonResponseBuilder localtimeEpoch(Integer localtimeEpoch) {
        timezoneJsonResponse.setLocaltimeEpoch(localtimeEpoch);
        return this;
    }

    /**
     * Local date and time
     */
    public TimezoneJsonResponseBuilder localtime(String localtime) {
        timezoneJsonResponse.setLocaltime(localtime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TimezoneJsonResponse build() {
        return timezoneJsonResponse;
    }
}