/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.weatherapi.com/v1";

    //TODO: Replace the key with an appropriate value
    public static String key = "";

}
